-- ==========================================
-- 1. PROFILES & AUTH SYNC
-- ==========================================

-- Create a table for user profiles linked to auth.users
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  full_name TEXT,
  phone TEXT,
  avatar_url TEXT,
  role TEXT DEFAULT 'admin' CHECK (role IN ('superadmin', 'admin', 'kasir')),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profile RLS Policies
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "Superadmins can manage everything" ON public.profiles FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'superadmin')
);

-- Function to automatically sync auth metadata to profiles table
CREATE OR REPLACE FUNCTION public.handle_auth_user_sync() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, first_name, last_name, full_name, phone, avatar_url, role)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'first_name', 
    new.raw_user_meta_data->>'last_name', 
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'phone',
    new.raw_user_meta_data->>'avatar_url',
    COALESCE(new.raw_user_meta_data->>'role', 'admin')
  )
  ON CONFLICT (id) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    full_name = EXCLUDED.full_name,
    phone = EXCLUDED.phone,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = timezone('asia/jakarta'::text, now());
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for sync on INSERT or UPDATE in auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP TRIGGER IF EXISTS on_auth_user_sync ON auth.users;
CREATE TRIGGER on_auth_user_sync
  AFTER INSERT OR UPDATE ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_auth_user_sync();

-- ==========================================
-- 2. POS CORE TABLES (Layar POS)
-- ==========================================

-- CATEGORIES
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now())
);
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- PRODUCTS
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    halal_certificate_number TEXT UNIQUE,
    certification_agency TEXT,
    halal_expired DATE,
    name TEXT NOT NULL,
    unit TEXT,
    barcode TEXT UNIQUE,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE RESTRICT,
    selling_price NUMERIC(15, 2) NOT NULL,
    min_stock INTEGER DEFAULT 0,
    status BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now())
);
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- SUPPLIERS
CREATE TABLE IF NOT EXISTS public.suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now())
);
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;

-- PURCHASES
CREATE TABLE IF NOT EXISTS public.purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT REFERENCES public.suppliers(id) ON DELETE RESTRICT,
    user_id UUID REFERENCES auth.users(id) ON DELETE RESTRICT,
    purchase_date DATE NOT NULL,
    total NUMERIC(15, 2) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now())
);
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;

-- STOCK BATCHES
CREATE TABLE IF NOT EXISTS public.stock_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    purchase_id BIGINT REFERENCES public.purchases(id) ON DELETE SET NULL,
    quantity INTEGER NOT NULL,
    purchase_price NUMERIC(15, 2) NOT NULL,
    expired_at DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now())
);
CREATE INDEX IF NOT EXISTS idx_products_expiry ON public.stock_batches (product_id, expired_at);
ALTER TABLE public.stock_batches ENABLE ROW LEVEL SECURITY;

-- PURCHASE ITEMS
CREATE TABLE IF NOT EXISTS public.purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id BIGINT REFERENCES public.purchases(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL,
    price NUMERIC(15, 2) NOT NULL,
    subtotal NUMERIC(15, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now())
);
ALTER TABLE public.purchase_items ENABLE ROW LEVEL SECURITY;

-- SALES
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE RESTRICT,
    invoice_number TEXT UNIQUE NOT NULL,
    subtotal NUMERIC(15, 2) NOT NULL,
    discount NUMERIC(15, 2) DEFAULT 0,
    tax NUMERIC(15, 2) DEFAULT 0,
    total NUMERIC(15, 2) NOT NULL,
    payment_method TEXT NOT NULL,
    cash_received NUMERIC(15, 2),
    change NUMERIC(15, 2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now())
);
CREATE INDEX IF NOT EXISTS idx_sales_created_at ON public.sales (created_at);
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;

-- SALE ITEMS
CREATE TABLE IF NOT EXISTS public.sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT REFERENCES public.sales(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE RESTRICT,
    stock_batch_id BIGINT REFERENCES public.stock_batches(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL,
    price NUMERIC(15, 2) NOT NULL,
    subtotal NUMERIC(15, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now())
);
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;

-- PURCHASE RETURNS
CREATE TABLE IF NOT EXISTS public.purchase_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id BIGINT REFERENCES public.purchases(id) ON DELETE RESTRICT,
    purchase_item_id BIGINT REFERENCES public.purchase_items(id) ON DELETE RESTRICT,
    stock_batch_id BIGINT REFERENCES public.stock_batches(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL,
    reason TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE RESTRICT,
    returned_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now()),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('asia/jakarta'::text, now())
);
ALTER TABLE public.purchase_returns ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 3. MASS RLS POLICIES
-- ==========================================

-- Policy to allow authenticated users to perform operations
-- This is a starting point, can be restricted by role later.
DO $$
DECLARE
    tbl_name TEXT;
    all_tables TEXT[] := ARRAY['categories', 'products', 'suppliers', 'purchases', 'purchase_items', 'stock_batches', 'sales', 'sale_items', 'purchase_returns'];
BEGIN
    FOREACH tbl_name IN ARRAY all_tables LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Authenticated users can select %I" ON public.%I', tbl_name, tbl_name);
        EXECUTE format('DROP POLICY IF EXISTS "Authenticated users can insert %I" ON public.%I', tbl_name, tbl_name);
        EXECUTE format('DROP POLICY IF EXISTS "Authenticated users can update %I" ON public.%I', tbl_name, tbl_name);
        
        EXECUTE format('CREATE POLICY "Authenticated users can select %I" ON public.%I FOR SELECT TO authenticated USING (true)', tbl_name, tbl_name);
        EXECUTE format('CREATE POLICY "Authenticated users can insert %I" ON public.%I FOR INSERT TO authenticated WITH CHECK (true)', tbl_name, tbl_name);
        EXECUTE format('CREATE POLICY "Authenticated users can update %I" ON public.%I FOR UPDATE TO authenticated USING (true)', tbl_name, tbl_name);
    END LOOP;
END $$;
